
---
- name: windows test
  hosts: all
  tasks:
    - name: Save the result of 'whoami' in 'whoami_out'
      win_command: 'osqueryi.exe --json "{{select}}"'
      register: response   
   
    - name: debug
      debug:
        msg: '{{item}}'
      loop: '{{response.stdout}}'
 